player_manager.AddValidModel( "Rebel Trooper 1", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_01.mdl" )
player_manager.AddValidModel( "Rebel Trooper 2", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_02.mdl" )
player_manager.AddValidModel( "Rebel Trooper 3", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_03.mdl" )
player_manager.AddValidModel( "Rebel Trooper 4", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_04.mdl" )
player_manager.AddValidModel( "Rebel Trooper 5", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_05.mdl" )
player_manager.AddValidModel( "Rebel Trooper 6", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_06.mdl" )
player_manager.AddValidModel( "Rebel Trooper 7", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_07.mdl" )
player_manager.AddValidModel( "Rebel Trooper 8", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_08.mdl" )
player_manager.AddValidModel( "Rebel Trooper 9", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_09.mdl" )
player_manager.AddValidModel( "Rebel Trooper Captain 1", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_01.mdl" )
player_manager.AddValidModel( "Rebel Trooper Captain 2", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_02.mdl" )
player_manager.AddValidModel( "Rebel Trooper Captain 3", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_03.mdl" )
player_manager.AddValidModel( "Rebel Trooper Captain 4", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_04.mdl" )
player_manager.AddValidModel( "Rebel Trooper Captain 5", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_05.mdl" )
player_manager.AddValidModel( "Rebel Trooper Captain 6", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_06.mdl" )
player_manager.AddValidModel( "Rebel Trooper Captain 7", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_07.mdl" )
player_manager.AddValidModel( "Rebel Trooper Captain 8", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_08.mdl" )
player_manager.AddValidModel( "Rebel Trooper Captain 9", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_09.mdl" )

list.Set( "PlayerOptionsModel",  "Rebel Trooper 1", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_01.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper 2", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_02.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper 3", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_03.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper 4", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_04.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper 4", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_05.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper 6", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_06.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper 7", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_07.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper 8", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_08.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper 9", 			"models/Player/SGG/Starwars/Rebels/r_trooper/male_09.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper Captain 1", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_01.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper Captain 2", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_02.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper Captain 3", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_03.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper Captain 4", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_04.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper Captain 5", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_05.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper Captain 6", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_06.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper Captain 7", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_07.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper Captain 8", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_08.mdl" )
list.Set( "PlayerOptionsModel",  "Rebel Trooper Captain 9", 	"models/Player/SGG/Starwars/Rebels/r_trooper_captain/male_09.mdl" )