player_manager.AddValidModel("Soviet Soldier","models/player/sev2/russian_soldier.mdl")
list.Set("PlayerOptionsModel","Soviet Soldier","models/player/sev2/russian_soldier.mdl")
player_manager.AddValidModel("Soviet Soldier 2","models/player/sev2/russian_soldier_2.mdl")
list.Set("PlayerOptionsModel","Soviet Soldier 2","models/player/sev2/russian_soldier_2.mdl")
player_manager.AddValidModel("Soviet Soldier 3","models/player/sev2/russian_soldier_3.mdl")
list.Set("PlayerOptionsModel","Soviet Soldier 3","models/player/sev2/russian_soldier_3.mdl")
player_manager.AddValidModel("Soviet Soldier 4","models/player/sev2/russian_soldier_4.mdl")
list.Set("PlayerOptionsModel","Soviet Soldier 4","models/player/sev2/russian_soldier_4.mdl")