list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_bowcaster",	title = "SW_Bowcaster" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dc15a",		title = "SW_DC-15A" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dc15s",		title = "SW_DC-15S" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dc15sa",		title = "SW_DC-15 Side Arm" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dc17",		title = "SW_DC-17" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dc17m_br",	title = "SW_DC-17m Blaster Rifle" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dc17m_sn",	title = "SW_DC-17m Sniper Rifle" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dh17",		title = "SW_DH-17" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_dlt19",		title = "SW_DLT-19" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_e11",		title = "SW_E-11" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_e5",			title = "SW_E-5" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_ee3",		title = "SW_EE-3" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_elg3a",		title = "SW_ELG-3A" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_ihr",		title = "SW_Imperial Heavy Repeater" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_kyd21",		title = "SW_KYD-21" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_se14c",		title = "SW_SE-14C" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_t21",		title = "SW_T-21" }  )
list.Add( "NPCUsableWeapons", { class = "npc_sw_weapon_752_westar34",	title = "SW_WESTAR-34" }  )
